# Generated by Django 6.1.1 on 2026-09-09 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil rasmi')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Telefon raqami')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, null=True, verbose_name='Jinsi')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat / Respublika')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar / Tuman')),
                ('address', models.TextField(blank=True, null=True, verbose_name="Aniq manzil (ko'cha, uy, xonadon)")),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pochta indeksi')),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Bonus ballari')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Telefon tasdiqlanganmi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Ro'yxatdan o'tgan vaqti")),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgartirilgan vaqti")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi profili',
                'verbose_name_plural': 'Foydalanuvchi profillari',
            },
        ),
    ]
