# Generated by Django 6.1.1 on 2026-09-12 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('region', models.CharField(max_length=100, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=100, verbose_name='Tuman / Shahar')),
                ('address', models.TextField(verbose_name='Aniq manzil')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Umumiy summa')),
                ('status', models.CharField(choices=[('pending', 'Kutishda'), ('confirmed', 'Tasdiqlangan'), ('on_the_way', "Yo'lda"), ('delivered', 'Yetkazib berilgan'), ('cancelled', 'Bekor qilingan')], default='pending', max_length=20, verbose_name='Buyurtma holati')),
                ('payment_method', models.CharField(choices=[('cash', 'Naqd pul orqali'), ('click', 'Click / Payme')], default='cash', max_length=20, verbose_name="To'lov turi")),
                ('is_paid', models.BooleanField(default=False, verbose_name="To'langanmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Buyurtma berilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sotib olingan narxi')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Soni')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Buyurtma')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='Mahsulot')),
            ],
            options={
                'verbose_name': 'Buyurtma elementi',
                'verbose_name_plural': 'Buyurtma elementlari',
            },
        ),
    ]
